INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','DAVLASTM','Давление на ур. станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','DAVLASTM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','DAVLAUMM','Давление на ур. моря');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','DAVLAUMM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','TENBVIDG','Вид барич. тенденции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','TENBVIDG_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','TENBVELR','Величина барич. тенденции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','TENBVELR_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmDavlenie','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYA','Номер АЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYAVLVID','Вид АЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYAVLVID_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYAINTENS','Интенсивность АЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYAINTENS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYATIMEN','Время начала АЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYATIMEN_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYATIMEK','Время конца АЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYATIMEK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','AYAPRIZPR','Признак наличия перерывов продолжительностью до 15 мин');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_AtmYavlenia','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','UPRVPAPP','Упругость водян. пара');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','UPRVPAPP_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','VLAOTVOM','Относит. влажность');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','VLAOTVOM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','NEDNASPR','Недостаток насыщенности');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','NEDNASPR_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','TOCHKAROS','Темп-ра точки росы');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','TOCHKAROS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_ElemVlazhnosti','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Geliograf','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Geliograf','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Geliograf','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Geliograf','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Geliograf','Hour','Час');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Geliograf','SOLNS','Продолжит.солн.сияния');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Geliograf','SOLNS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Geliograf','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Gigrograf','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Gigrograf','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Gigrograf','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Gigrograf','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Gigrograf','Hour','Час');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Gigrograf','VLOVZ','Отн. влажность');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Gigrograf','VLOVZ_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Gigrograf','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','VIDHORIS','Дальность видимости (КН-01)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','VIDHORIS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLOKOLB','Общее количество облачности в баллах');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLOKOLB_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLNKOLB','Количество облаков нижнего яруса в баллах');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLNKOLB_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLFORVL','Форма облаков верхнего яруса');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLFORVL_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLFORSL','Форма облаков среднего яруса');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLFORSL_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLFORVR','Форма облаков вертикального развития');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLFORVR_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLSLSLK','Слоистые и слоисто-кучевые облака');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLSLSLK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLSLDRD','Слоисто-дожд. и разорванно-дожд. облака');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLSLDRD_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLVINGM','Высота нижней границы облаков в метрах');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLVINGM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLPNNUS','Признак наличия облачн. ниже ур. станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','OBLPNNUS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','SOVON','Способ опр.высоты нижней границы. 0 - инструментально, 1 - визуально');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Oblachnost','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','NOBLED','Порядковый номер случая изморозевого-гололедного отложения в данном сезоне');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','NOBLED_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE1','Шифр первого вида отложения');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE1_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE2','Шифр второго вида отложения');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE2_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE3','Шифр третьего вида отложения');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE3_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE4','Шифр четвертого вида отложения');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE4_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE5','Шифр пятого вида отложения');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','CODE5_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDVRENV','Время начала случая отложения в целых часах');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDVRENV_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDPRSTN','Продолжительность стадии нарастания отложения в час');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDPRSTN_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDPRODV','Продолжительность случая отложения в целых часах');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDPRODV_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDTEMNM','Значение температуры воздуха в начале отложения');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDTEMNM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBVETNNM','Значение направления ветра в начале отложения');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBVETNNM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBVETSNM','Значение скорости ветра в начале отложения');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBVETSNM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDTEMMM','Температура воздуха при отложении максимальных размеров');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDTEMMM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBVETNMM','Направление ветра при отложении максимальных размеров');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBVETNMM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBVETSMM','Скорость ветра при отложении максимальных размеров');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBVETSMM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDPRPER','Признак перехода случая гололедно-изморозевого отложения через границы месяца');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDPRPER_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDPRD1H','Продолжительность 1-ой части случая отложения при его переходе на следующий месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','OBDPRD1H_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM1ST','Диаметр отложения на 1-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM1ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH1ST','Толщина отложения на 1-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH1ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS1ST','Масса отложения на 1-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS1ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM2ST','Диаметр отложения на 2-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM2ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH2ST','Толщина отложения на 2-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH2ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS2ST','Масса отложения на 2-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS2ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM3ST','Диаметр отложения на 3-й стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM3ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH3ST','Толщина отложения на 3-й стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH3ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS3ST','Масса отложения на 3-й стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS3ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM4ST','Диаметр отложения на 4-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM4ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH4ST','Толщина отложения на 4-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH4ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS4ST','Масса отложения на 4-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS4ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM5ST','Диаметр отложения на 5-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM5ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH5ST','Толщина отложения на 5-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH5ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS5ST','Масса отложения на 5-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS5ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM6ST','Диаметр отложения на 6-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','DIAM6ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH6ST','Толщина отложения на 6-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','TOLSH6ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS6ST','Масса отложения на 6-ой стадии нарастания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','MAS6ST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Obled','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','NOOA','Счетчик случаев ООЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','DAYBEG','День начала ООЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','DAYEND','День окончания ООЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAVREMN','Время начала ООЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAVREMN_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAVREMK','Время конца ООЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAVREMK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAVID','Вид ООЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAVID_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAHAR1','Первая характеристика ООЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAHAR1_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAHAR2','Вторая характеристика ООЯ');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAHAR2_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAPRPER','Признак перехода ООЯ через границы месяца');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAPRPER_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAPROD','Продолжит. первой части ООЯ при переходе с предыдущего месяца, час.мин');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','OOAPROD_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OOA','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OsadkiKM1','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OsadkiKM1','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OsadkiKM1','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OsadkiKM1','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OsadkiKM1','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OsadkiKM1','SASYMSR','Сумма осадков за период между сроками');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OsadkiKM1','SASYMSR_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_OsadkiKM1','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','NRAIN','Номер дождя');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','SCHINT','Счетчик периодов с равной интенсивностью');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAPRPER','Признак перехода дождя через границы месяца');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAPRPER_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','DAYBEG','День начала дождя');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','DAYEND','День окончания дождя');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','DAY_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','TIMEBEG','Время начала дождя');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','TIMEBEG_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','NPeriod','Порядк. номер периода дождя с постоянной интенсивностью');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAKOL1P','Количество осадков за 1-ю часть дождя, в случае перехода дождя с предыдущего месяца');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAKOL1P_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSADPROD','Продолжительность дождя в час.мин');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSADPROD_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAKOLDZH','Количество осадков за дождь, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAKOLDZH_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSASINTD','Средняя интенсивность дождя, мм/мин');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSASINTD_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSASYMPR','Суммарная продолжительность дождя в час.мин');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSASYMPR_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSASKOLD','Суммарное количество осадков за дождь');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSASKOLD_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAINT','Средняя интенсивность всего дождя, мм/мин');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAINT_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','TIME_INT_END','Время окончания периода с постоянной интенсивностью');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','TIME_INT_END_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAINTKOL','Кол-во осадков от начала дождя на момент окончания периода с пост.интенс.');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAINTKOL_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAINTPERIOD','Средняя интенсивность дождя за период, мм/мин');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','OSAINTPERIOD_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','Hour','Час');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','Min_beg','время начала дождя в минутах 0-59');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','Min_end','время окончания дождя в минутах 0-59');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R1','количество осадков от начала дождя на конец 1-го 10-мин интервала, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R1_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R2','количество осадков от начала дождя на конец 2-го 10-мин интервала, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R2_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R3','количество осадков от начала дождя на конец 3-го 10-мин интервала, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R3_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R4','количество осадков от начала дождя на конец 4-го 10-мин интервала, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R4_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R5','количество осадков от начала дождя на конец 5-го 10-мин интервала, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R5_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R6','количество осадков от начала дождя на конец 6-го 10-мин интервала, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','R6_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pluviograf_R','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SOSTPPCHV8','Состояние поверхности почвы в срок ближ. в 8ч');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SOSTPPCHV8_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SOSTPPCHV20','Состояние поверхности почвы в срок ближ. в 20ч');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SOSTPPCHV20_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SOSTPPU','Признак кодирования состояния поверхности почвы по таблице 12 или 13');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','VISOTA1R','Высота снежного  покрова  (см) по 1-й рейке');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','VISOTA1R_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','VISOTA2R','Высота снежного  покрова  (см) по 2-й рейке');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','VISOTA2R_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','VISOTA3R','Высота снежного  покрова  (см) по 3-й рейке');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','VISOTA3R_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SNESTEPV','Степень покрытия окрестности станции снегом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SNESTEPV_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SNEPHARZ','Характер залегания снежного покрова');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','SNEPHARZ_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvaSneg','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL02E','Темп-ра почвы на глуб. 2 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL02E_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL05E','Темп-ра почвы на глуб. 5 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL05E_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL10E','Темп-ра почвы на глуб. 10 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL10E_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL15E','Темп-ра почвы на глуб. 15 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL15E_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL20E','Темп-ра почвы на глуб. 20 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL20E_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL40E','Темп-ра почвы на глуб. 40 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','TEMGL40E_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermEst','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB080','Темп-ра почвы на глуб. 80 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB080_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB120','Темп-ра почвы на глуб. 120 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB120_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB160','Темп-ра почвы на глуб. 160 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB160_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB240','Темп-ра почвы на глуб. 240 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB240_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB320','Темп-ра почвы на глуб. 320 см под естеств. покровом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','TGLUB320_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','SNEPVIST','Высота снежного покрова у почвенных термометров');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','SNEPVIST_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermGlub','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','TEMGL05O','Темп-ра почвы на глуб. 5 см под оголен. поверх.');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','TEMGL05O_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','TEMGL10O','Темп-ра почвы на глуб. 10 см под оголен. поверх.');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','TEMGL10O_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','TEMGL15O','Темп-ра почвы на глуб. 15 см под оголен. поверх.');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','TEMGL15O_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','TEMGL20O','Темп-ра почвы на глуб. 20 см под оголен. поверх.');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','TEMGL20O_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermOgol','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEMPOVPM','Темп-ра поверхн. почвы в срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEMPOVPM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEMPSPIR','Темп-ра пов. почвы по спирту мин. т-ра');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEMPSPIR_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEIPOVPM','Миним. темп-ра поверхности почвы между сроками');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEIPOVPM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEAPOVPM','максим. темп-ра поверхности почвы между сроками');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEAPOVPM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEMPPPVS','Темп-ра поверхности почвы по максимальному термометру после встряхивания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','TEMPPPVS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_PochvTermPov','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','POGOMSNV','Погода между сроками набл.');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','POGOMSNV_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','POGODSNV','Погода в срок набл.');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','POGODSNV_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Pogoda','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNESTPOKT','Степень покрытия маршрута снегом по числу точек (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNESTPOKT_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNESTPLK','Степень покрытия маршрута ледяной коркой на почве (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNESTPLK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNESTPOKO','Степень покрытия окрестности снегом (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNESTPOKO_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGHARP','Состояние поверхности почвы под снегом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGTSCHW','Толщина слоя чистой воды под снегом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGTSCHW_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGSVIS','Средняя высота снежного покрова по маршруту снегосъемок, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGSVIS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEVISMA','Максимальная высота снежного покрова по маршруту, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEVISMA_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEVISMI','Минимальная высота снежного покрова по маршруту, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEVISMI_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNESRTLK','Толщина ледяной корки под снегом, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNESRTLK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGTSNW','Толщина слоя  снега насыщенного водой, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGTSNW_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGHARZ','Характер залегания  снежного  покрова, по маршруту, шифр');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGHARZ_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGSRPL','Средняя плотность снега, г/ см\3');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','SNEGSRPL_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaBalki','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNESTPOKT','Степень покрытия маршрута снегом по числу точек (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNESTPOKT_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNESTPLK','Степень покрытия маршрута ледяной коркой на почве (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNESTPLK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNESTPOKO','Степень покрытия окрестности снегом (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNESTPOKO_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGHARP','Состояние поверхности почвы под снегом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGTSCHW','Толщина слоя чистой воды под снегом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGTSCHW_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGSVIS','Средняя высота снежного покрова по маршруту снегосъемок, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGSVIS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEVISMA','Максимальная высота снежного покрова по маршруту, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEVISMA_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEVISMI','Минимальная высота снежного покрова по маршруту, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEVISMI_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNESRTLK','Толщина ледяной корки под снегом, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNESRTLK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGTSNW','Толщина слоя  снега насыщенного водой, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGTSNW_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGHARZ','Характер залегания  снежного  покрова, по маршруту, шифр');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGHARZ_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','HARPOKROVA','Характер снежного  покрова по маршруту, шифр');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','HARPOKROVA_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGSRPL','Средняя плотность снега, г/ см\3');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','SNEGSRPL_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaLes','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNESTPOKT','Степень покрытия маршрута снегом по числу точек (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNESTPOKT_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNESTPLK','Степень покрытия маршрута ледяной коркой на почве (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNESTPLK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNESTPOKO','Степень покрытия окрестности снегом (в баллах)');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNESTPOKO_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGHARP','Состояние поверхности почвы под снегом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGTSCHW','Толщина слоя чистой воды под снегом');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGTSCHW_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGSVIS','Средняя высота снежного покрова по маршруту снегосъемок, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGSVIS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEVISMA','Максимальная высота снежного покрова по маршруту, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEVISMA_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEVISMI','Минимальная высота снежного покрова по маршруту, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEVISMI_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNESRTLK','Толщина ледяной корки под снегом, мм');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNESRTLK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGTSNW','Толщина слоя  снега насыщенного водой, см');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGTSNW_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGHARZ','Характер залегания  снежного  покрова, по маршруту, шифр');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGHARZ_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','HARPOKROVA','Характер снежного  покрова по маршруту, шифр');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','HARPOKROVA_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGSRPL','Средняя плотность снега, г/ см\3');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','SNEGSRPL_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_SnegosiemkaPole','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Termograf','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Termograf','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Termograf','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Termograf','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Termograf','Hour','Час');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Termograf','TEMVZ','Темп-ра воздуха');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Termograf','TEMVZ_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Termograf','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','VETNAPRM','Направление ветра');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','VETNAPRM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','VETSKORM','Средняя скор. ветра');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','VETSKORM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','VETSKMAK','Макс. скор. ветра');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','VETSKMAK_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','VETHAR','Характеристика регулярности ветра');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','VETHAR_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Veter','STATION_CODE','Код станции');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','DATE_VAL','Дата/время');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','Year','Год');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','Month','Месяц');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','Day','День');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','Srok','Срок');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEMVOZDM','Темп-ра воздуха в срок по сухому термометру');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEMVOZDM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEMVSMSM','Темп-ра воздуха в срок по смоченному термометру');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEMVSMSM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEMVPRNU','Признак наличия льда на батисте');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEVSPIRT','Темп-ра воздуха в срок по спирту минимального термометра');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEVSPIRT_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEIVOZSM','Миним. темп-ра воздуха за период между сроками');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEIVOZSM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEAVOZSM','Максим. темп-ра воздуха за период между сроками');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEAVOZSM_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','ZASHKALMAX','Признак зашкаливания максим. термометра');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEMVMPVS','Темп-ра воздуха по максим. термометру после встряхивания');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','TEMVMPVS_Q','Признак качества');
INSERT INTO fields_description(table_name, column_name, description) VALUES ('IS_Vozdyh','STATION_CODE','Код станции');